language: node_js
node_js:
- '4.2'
sudo: false
services:
- mongodb
before_script:
- npm shrinkwrap
after_script: npm run report-coverage
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: leave_calendar
  env: leaveCalendar-env
  bucket_name: leave-calendar
  access_key_id: AKIAJ6LKDXRWXBMCFCKA
  secret_access_key:
    secure: hLxstAvensWf63T/FlIh1Xxx+Riv5d/ldsimezmTps+cfycj5ATg7fgK6+hDLz/urKF2i3dmtvqcu3dj+RwpgYJX1P1Ma9gQxpTaWPL9J7yIUdHmlWpZdWXuYzOp4m7hrvb/6RQFkVQB+CeUXQuovnh8sset1JV877H3ZdK6NWPLjFOo20l4WY0HiqykUZYCWbzEen2ETp64uhR8pvpbalHPnVLjtblAU0U6biTDXZd8j+/7IOI0lAHGKd26Hq++QQcVPm7UA9ND0GJMd2dHW435MVuTnogSY0ht7F5862fG/VR3Xo4j4VyCl6SGV4cGJicEtoiR3V+9qiXXpBJMARaXJbRWnn4FN2n/1BcP+QdzORds1lqFLCLRykat5TVTMeM005f1LoWjXYTz/vgqdW8j9xxSqwkxSdzNRn0YGDNjLXiL5dmzUPMUk/0ntov1+96XLh+FRDcAJAztCqjwSn01mWQKMnWk72+nuolVh87d8WW1f7pGagPO9G4HhLj5P2W1Lvzy7PcoVrQnDHfTv4Saoun6FFSbSsA0DxjtSu9TybCXzZijlfQGYFdqw2aaDj4DSEPNcaZxAiEnnvOBp5VNBcpuBiiEr3mX7vZvZAY3pFjLFAu3vUQTbgryDAK4/fi4bUxwG/DUIN1mxJhtvhhUS1mOolGeuz7k2MRculo=
  on:
    tags: true
