language: node_js
node_js:
- '4.2'
sudo: false
services:
- mongodb
before_script:
- npm shrinkwrap
after_script: npm run report-coverage
deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: leave_calendar
  env: leaveCalendar-env
  bucket_name: leave-calendar
  access_key_id: AKIAJ6LKDXRWXBMCFCKA
  secret_access_key:
    secure: avmJByVGKWwHSDSS/phcUvM6jbWgpdpYAoQpFKA2SE+/NreB7u9rrEOjLWF4MIRuroVrHrm1uY/238VdoC/eXJ/+bFS3IwOfUYEb7FLRfnpojEeE2EwuI1Cj1JsuXGjP4+IuIOGJeo2haO7vTEhyOM++fdcNhaQZJKb9YWWdx2rOAKtY+LBVPXMDIPkmr1c6RIFsB1CCSD3BKyDGb2jUnbJgNBqKXz9Qqz22Q6ZtOIfEHL8n1Z4spFqq8s/eLtmXaqF6Dnu9uJO/Ymwf9ildX126hLoe2HDpw1+lGESQlS+7o6tiiNrLGoPnzvgA53dqgBMkjRnNJEH1Dh+npRMaQNG4+CibCdDImw5tyD2Lv7GhwpBSurVspHaLmbdITry0VnBoBfwzbfG2yvXMxW4z4v/DBXNqNHI1p7YAXOB9DusFsFUoIJtlAUHUdjCF3CoqcVXCVreuUjbsuCD5JmW95pvmQRtDJHu8CBAz+yNbF6II0HFhyL3a/JbntnbDjx8zR/3ec9wA/2MsrHgyhwL94hnVcxrHZ6oyVryiw7l8GQuMjOu4X9mmhLb3+ceiKUBVg6kimeWzEmiaZiX2CqHsMTIUCeDb4sj9x2GbYWgvrVQwXozNIz/zmbQsNiq9hpopk0M91RART8RVgPBHRM+Nr2P5amGOoe8q/vp0qmf4iB0=
  on:
    tags: true
