language: node_js
node_js:
- '4.2'
sudo: false
services:
- mongodb
before_script:
- npm shrinkwrap
script: ./build.sh
after_script: npm run report-coverage
before_deploy: 'echo "$(grep -v "public" .gitignore)" > .gitignore'
deploy:
  skip_cleanup: true
  zip_file: leaveTimeline.zip
  provider: elasticbeanstalk
  region: us-west-2
  app: Leave Timeline
  env: leaveTimeline-env
  bucket_name: elasticbeanstalk-us-west-2-286035534108
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    tags: true
